----1 CREATE TABLE

CREATE TABLE STUDENTS(
ID INT PRIMARY KEY NOT NULL,
NAME TEXT NOT NULL,
AGE INT NOT NULL,
CITY CHAR(20),
GRADE REAL NOT NULL
);
---- 2 STUDENTS INSERT

INSERT INTO STUDENTS ( ID, NAME, AGE, CITY, GRADE)
VALUES
 (1, "NOAH", 15, "TEL AVIV", 92.5),
 (2, "LIAM", 16, "HAIFA", 88.0),
 (3, "MAIA", 15, "NETANYA", 95.0),
 (4, "OMER", 17, "JERUSALEM", 81.5);

----- 3 SELECT QUERIES
--- 1
SELECT * FROM STUDENTS;

---2
SELECT NAME, GRADE FROM STUDENTS;

---3
SELECT * FROM STUDENTS
WHERE GRADE > 90;

--4
SELECT * FROM STUDENTS 
WHERE NAME LIKE "M%";

--5
SELECT AVG (GRADE) 
FROM STUDENTS;

--6
SELECT * FROM STUDENTS
WHERE GRADE > (SELECT AVG (GRADE) FROM STUDENTS);

------- 4 changes
UPDATE STUDENTS SET GRADE = 90
WHERE ID = 2;

------- 5 delete by city
DELETE FROM STUDENTS
WHERE CITY LIKE 'N%';

------- 6 DELETE

DELETE FROM STUDENTS 
WHERE GRADE = 88.0;

------ 7 DROP TABLE

DROP TABLE STUDENTS;


